### ISSUE TITLE
Possibly outdated on 1.13.4

### ISSUE THREAD

**Issue by FlameSoulis** [rakso20000/MenuBuster#2]
```
[DEBUG @ 06:30:42 | IPA/Loader] Adding info for MenuBuster.dll
[WARNING @ 06:30:42 | IPA/Loader/Features] Encountered old features used. They no longer do anything, please move to the new format.
```
Seems the plugin may be outdated. Any plans to update it?

**Comment by rakso20000** [comment]
To my knowledge it's been broken since some steamvr update.
We tried fixing it but didn't have much luck so unfortunately right now there aren't any plans to update it.
